### ISSUE TITLE
Tuple of strings as sender

### ISSUE THREAD

**Issue by brickZA** [jek/blinker#1]
As of blinker 1.3 we can now reliably use strings as senders, but it seems that the next logical step, using a tuple of strings, does not work reliably.

if I do:

```py
def blah(sender, **kwargs):
    print sender, kwargs

s = blinker.Signal()

s.connect(blah, ('ab', 'cde'))
s.send(('ab', 'cde'))
```
The call to s.send(('ab', 'cde')) will result in blah() sometimes being called, sometimes not.

Using a tuple of strings seems, to me at least, a nice way to have a finer grained signal subscription mechanism without having separate signals.

**Comment by jek** [comment]
Unfortunately I don't see supporting this at the moment- chasing down interned types in structures seems like an endless rabbit hole.
