### ISSUE TITLE
Can't connect functools.partial

### ISSUE THREAD

**Issue by ksonj** [jek/blinker#19]
It seems to not be possible to connect a `functools.partial` function to `signal.connect()`. Is that intended behavior?

**Comment by jek** [comment]
Have not seen that. Can you provide a test case?

```
>>> from blinker import signal
>>> from functools import partial
>>> def full(private, sender, **kw):
...     print((private, sender, kw))
...
>>> p = partial(full, 'private arg')
>>> signal('test').connect(p)
<functools.partial object at 0x370900>
>>> signal('test').send(123, abc=456)
('private arg', 123, {'abc': 456})
[(<functools.partial object at 0x370900>, None)]
```

**Comment by ksonj** [comment]
Alright, that works. But try executing this little script:

    from blinker import signal
    from functools import partial
    
    
    def func(sender):
        pass
    
    ready = signal('ready')
    
    ready.connect(partial(func))
    print(ready.receivers)
    
    p = partial(func)
    ready.connect(p)
    print(ready.receivers)

Why are there no receivers on the signal after registering the anonymous partial? The weirdest thing is, that when I type that into a REPL instead of executing it as a script, it works as expected.

**Comment by jek** [comment]
Your anonymous partial is falling out of scope and getting gc'd by Python.  Lock it in with `weak=False` like this:

```python
from blinker import signal
from functools import partial


def func(sender):
    pass

ready = signal('ready')

ready.connect(partial(func), weak=False)
print(ready.receivers)
```
