### ISSUE TITLE
Problem in _saferef.py

### ISSUE THREAD

**Issue by pwrdby** [jek/blinker#20]
My code reported this error: 
File "/home/lib/python3.4/site-packages/blinker/_saferef.py", line 197, in calculate_key
    return (id(get_self(target)), id(get_func(target)))
AttributeError: 'function' object has no attribute '__self__' . 
When i print(dir(target)) i got this:
['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'accept', 'im_func', 'im_self', 'is_signal_handler']

There is no '__self__', just 'im_self'. I tried to change the code on line 50 in file _saferef.py: 
from if sys.version_info < (3,):
to if sys.version_info > (3,):

and my code works. Is it a mistake in my code or is it a bug ?
Thank you for your patience.

**Comment by jek** [comment]
Can you paste a test case that produces that traceback? All the tests pass on 3.4, so perhaps something is missing in the tests or in the (increasingly creaky) saferef implementation.

**Comment by pwrdby** [comment]
I ran more tests and I found out, that bug is in lib mongoengine, which assumed blinker version 0.9. 
Sorry for misunderstanding.
