### ISSUE TITLE
Using object proxy as sender do not work

### ISSUE THREAD

**Issue by reidfaiv** [jek/blinker#37]
When application uses object proxy as sender in connect then signal is never delivered. This is due use of object id, which is different for real object and proxy.

For example when using https://pypi.python.org/pypi/lazy-object-proxy the signal is never received.

    import blinker
    from lazy_object_proxy import Proxy

    class X(object):
        def receive(self, *args, **kwargs):
          print 'got signal'
        def send(self):
          print 'sending signal'
          test_signal.send(self)

    x = X()

    def get_x():
        return x

    x_proxy = Proxy(get_x)  # Lazy object proxy is useful sometimes

    test_signal = blinker.Signal()
    test_signal.connect(x_proxy.receive, sender=x_proxy)

    x_proxy.send()  # never received because id(x) != id(x_proxy)

Even though x and x_proxy have different id values, the normal equal comparison works, as well as __hash__() returns same value:

    >>> id(x) == id(x_proxy)
    False
    >>> x == x_proxy
    True
    >>> hash(x) == hash(x_proxy)
    True

It is similar issue as reported in #30 and similar solution (using hash) would help.

**Comment by jek** [comment]
`hash()` values are not unique across types (or guaranteed unique amongst instances of types), which is why identity is used now.
