### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by femtotrader** [jek/blinker#8]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with blinker. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable blinker on @Sourcegraph by going to https://sourcegraph.com/github.com/jek/blinker and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by jek** [comment]
Done.
