### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by femtotrader** [jek/blinker#9]
Hello,

It will be nice to add Continuous Integration.
Please go to https://travis-ci.org/ and enable your `blinker` project

add a `.travis.yml` file with

    language: python
    python:
      - "2.7"
      - "3.2"
      - "3.3"
      - "3.4"

    # command to install dependencies
    install:
      - "pip install ."

    # command to run tests
    script: nosetests

then you can push your code.

Kind regards

**Comment by CodeMan99** [comment]
Based on PRs, [travisci](https://travis-ci.org/jek/blinker) is set up.

**Comment by femtotrader** [comment]
WARNING: We were unable to find a .travis.yml file. This may not be what you
  want. Build will be run with default settings.

A `.travis.yml` file at root directory is necessary because it seems that Travis consider by default Ruby projects... not Python.

**Comment by femtotrader** [comment]
Adding a badge will be also a good idea

   [![Build Status](https://travis-ci.org/jek/blinker.svg?branch=master)](https://travis-ci.org/jek/blinker)

**Comment by jek** [comment]
Travis is now setup, thanks!
